/**
 * Authentication Types
 * TypeScript definitions for auth-related data
 */

import { User as SupabaseUser, Session } from '@supabase/supabase-js';

// Database schema type (will be auto-generated by Supabase CLI)
export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          phone: string | null;
          date_of_birth: string | null;
          blood_type: string | null;
          allergies: string | null;
          chronic_conditions: string | null;
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['profiles']['Row'], 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>;
      };
    };
  };
};

// User profile from database
export interface UserProfile {
  id: string;
  email: string;
  fullName: string | null;
  phone: string | null;
  dateOfBirth: string | null;
  bloodType: string | null;
  allergies: string | null;
  chronicConditions: string | null;
  avatarUrl: string | null;
  createdAt: string;
  updatedAt: string;
}

// Auth state
export interface AuthState {
  user: SupabaseUser | null;
  session: Session | null;
  profile: UserProfile | null;
  loading: boolean;
  error: AuthError | null;
}

// Auth error
export interface AuthError {
  message: string;
  code?: string;
  status?: number;
}

// Sign up credentials
export interface SignUpCredentials {
  email: string;
  password: string;
  fullName?: string;
  phone?: string;
}

// Sign in credentials
export interface SignInCredentials {
  email: string;
  password: string;
}

// Password reset
export interface PasswordResetRequest {
  email: string;
}

// Update password
export interface PasswordUpdateRequest {
  newPassword: string;
}

// Update profile
export interface ProfileUpdateRequest {
  fullName?: string;
  phone?: string;
  dateOfBirth?: string;
  bloodType?: string;
  allergies?: string;
  chronicConditions?: string;
  avatarUrl?: string;
}

// Auth event types
export type AuthEventType =
  | 'SIGNED_IN'
  | 'SIGNED_OUT'
  | 'TOKEN_REFRESHED'
  | 'USER_UPDATED'
  | 'PASSWORD_RECOVERY';

// Auth change event
export interface AuthChangeEvent {
  event: AuthEventType;
  session: Session | null;
}

// Auth response
export interface AuthResponse<T = any> {
  data: T | null;
  error: AuthError | null;
}
