/**
 * Authentication Types
 * TypeScript definitions for auth-related data
 */

import { User as SupabaseUser, Session } from '@supabase/supabase-js';

// Blood type options
export type BloodType = 'A+' | 'A-' | 'B+' | 'B-' | 'AB+' | 'AB-' | 'O+' | 'O-';

export const BLOOD_TYPE_OPTIONS: { value: BloodType; label: string }[] = [
  { value: 'A+', label: 'A+' },
  { value: 'A-', label: 'A−' },
  { value: 'B+', label: 'B+' },
  { value: 'B-', label: 'B−' },
  { value: 'AB+', label: 'AB+' },
  { value: 'AB-', label: 'AB−' },
  { value: 'O+', label: 'O+' },
  { value: 'O-', label: 'O−' },
];

// Database schema type (will be auto-generated by Supabase CLI)
export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          first_name: string | null;
          last_name: string | null;
          full_name: string | null;
          gender: string | null;
          phone: string | null;
          date_of_birth: string | null;
          blood_type: string | null;
          allergies: string | null;
          chronic_conditions: string | null;
          height_cm: number | null;
          weight_kg: number | null;
          emergency_contact_name: string | null;
          emergency_contact_phone: string | null;
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['profiles']['Row'], 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>;
      };
    };
  };
};

// User profile from database
export interface UserProfile {
  id: string;
  email: string;
  firstName: string | null;
  lastName: string | null;
  fullName: string | null;
  gender: Gender | null;
  phone: string | null;
  dateOfBirth: string | null;
  bloodType: BloodType | null;
  allergies: string | null;
  chronicConditions: string | null;
  heightCm: number | null;
  weightKg: number | null;
  emergencyContactName: string | null;
  emergencyContactPhone: string | null;
  avatarUrl: string | null;
  createdAt: string;
  updatedAt: string;
}

// Auth state (immutable — always replace via setState, never mutate)
export interface AuthState {
  readonly user: SupabaseUser | null;
  readonly session: Session | null;
  readonly profile: UserProfile | null;
  readonly loading: boolean;
  readonly error: AuthError | null;
}

// Auth error
export interface AuthError {
  readonly message: string;
  readonly code?: string;
  readonly status?: number;
}

// Gender options
export type Gender = 'male' | 'female' | 'other' | 'prefer_not_to_say';

export const GENDER_OPTIONS: { value: Gender; label: string }[] = [
  { value: 'male', label: 'Male' },
  { value: 'female', label: 'Female' },
  { value: 'other', label: 'Other' },
  { value: 'prefer_not_to_say', label: 'Prefer not to say' },
];

// Common allergy options for medical profiles
export const ALLERGY_OPTIONS: string[] = [
  'Penicillin',
  'Sulfa Drugs',
  'Aspirin',
  'Ibuprofen',
  'Latex',
  'Peanuts',
  'Tree Nuts',
  'Shellfish',
  'Fish',
  'Eggs',
  'Milk / Dairy',
  'Wheat / Gluten',
  'Soy',
  'Bee Stings',
  'Dust Mites',
  'Pollen',
  'Pet Dander',
  'Mold',
];

// Common chronic condition options for medical profiles
export const CHRONIC_CONDITION_OPTIONS: string[] = [
  'Diabetes Type 1',
  'Diabetes Type 2',
  'Hypertension',
  'Asthma',
  'Heart Disease',
  'Chronic Kidney Disease',
  'COPD',
  'Arthritis',
  'Thyroid Disorder',
  'Epilepsy',
  'Anemia',
  'Sickle Cell Disease',
  'Depression',
  'Anxiety Disorder',
  'Migraine',
  'Osteoporosis',
  'Cancer',
  'Hepatitis',
  'HIV/AIDS',
  'Lupus',
];

// Sign up credentials
export interface SignUpCredentials {
  email: string;
  password: string;
  firstName: string;
  lastName: string;
  dateOfBirth: string;
  gender: Gender;
  countryCode: string;
  phone: string;
  captchaToken?: string;
}

// Sign in credentials
export interface SignInCredentials {
  email: string;
  password: string;
  captchaToken?: string;
}

// Password reset
export interface PasswordResetRequest {
  email: string;
}

// Update password
export interface PasswordUpdateRequest {
  newPassword: string;
}

// Update profile
export interface ProfileUpdateRequest {
  firstName?: string;
  lastName?: string;
  fullName?: string;
  gender?: Gender;
  phone?: string;
  dateOfBirth?: string;
  bloodType?: BloodType;
  allergies?: string;
  chronicConditions?: string;
  heightCm?: number;
  weightKg?: number;
  emergencyContactName?: string;
  emergencyContactPhone?: string;
  avatarUrl?: string;
}

// Auth event types
export type AuthEventType =
  | 'SIGNED_IN'
  | 'SIGNED_OUT'
  | 'TOKEN_REFRESHED'
  | 'USER_UPDATED'
  | 'PASSWORD_RECOVERY';

// Auth change event
export interface AuthChangeEvent {
  event: AuthEventType;
  session: Session | null;
}

// Auth response (generic result wrapper — similar to Rust's Result<T, E>)
export interface AuthResponse<T = unknown> {
  readonly data: T | null;
  readonly error: AuthError | null;
}
