/**
 * Authentication Types
 * TypeScript definitions for auth-related data
 */

import { User as SupabaseUser, Session } from '@supabase/supabase-js';

// Blood type options
export type BloodType = 'A+' | 'A-' | 'B+' | 'B-' | 'AB+' | 'AB-' | 'O+' | 'O-';

export const BLOOD_TYPE_OPTIONS: { value: BloodType; label: string }[] = [
  { value: 'A+', label: 'A+' },
  { value: 'A-', label: 'A−' },
  { value: 'B+', label: 'B+' },
  { value: 'B-', label: 'B−' },
  { value: 'AB+', label: 'AB+' },
  { value: 'AB-', label: 'AB−' },
  { value: 'O+', label: 'O+' },
  { value: 'O-', label: 'O−' },
];

// Database schema type (will be auto-generated by Supabase CLI)
export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          first_name: string | null;
          last_name: string | null;
          full_name: string | null;
          gender: string | null;
          phone: string | null;
          date_of_birth: string | null;
          blood_type: string | null;
          allergies: string | null;
          chronic_conditions: string | null;
          height_cm: number | null;
          weight_kg: number | null;
          emergency_contact_name: string | null;
          emergency_contact_phone: string | null;
          insurance_provider: string | null;
          insurance_policy_number: string | null;
          medical_notes: string | null;
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['profiles']['Row'], 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>;
      };
    };
  };
};

// User profile from database
export interface UserProfile {
  id: string;
  email: string;
  firstName: string | null;
  lastName: string | null;
  fullName: string | null;
  gender: Gender | null;
  phone: string | null;
  dateOfBirth: string | null;
  bloodType: BloodType | null;
  allergies: string | null;
  chronicConditions: string | null;
  heightCm: number | null;
  weightKg: number | null;
  emergencyContactName: string | null;
  emergencyContactPhone: string | null;
  insuranceProvider: string | null;
  insurancePolicyNumber: string | null;
  medicalNotes: string | null;
  avatarUrl: string | null;
  createdAt: string;
  updatedAt: string;
}

// Auth state
export interface AuthState {
  user: SupabaseUser | null;
  session: Session | null;
  profile: UserProfile | null;
  loading: boolean;
  error: AuthError | null;
}

// Auth error
export interface AuthError {
  message: string;
  code?: string;
  status?: number;
}

// Gender options
export type Gender = 'male' | 'female' | 'other' | 'prefer_not_to_say';

export const GENDER_OPTIONS: { value: Gender; label: string }[] = [
  { value: 'male', label: 'Male' },
  { value: 'female', label: 'Female' },
  { value: 'other', label: 'Other' },
  { value: 'prefer_not_to_say', label: 'Prefer not to say' },
];

// Sign up credentials
export interface SignUpCredentials {
  email: string;
  password: string;
  firstName: string;
  lastName: string;
  dateOfBirth: string;
  gender: Gender;
  countryCode: string;
  phone: string;
  captchaToken?: string;
}

// Sign in credentials
export interface SignInCredentials {
  email: string;
  password: string;
  captchaToken?: string;
}

// Password reset
export interface PasswordResetRequest {
  email: string;
}

// Update password
export interface PasswordUpdateRequest {
  newPassword: string;
}

// Update profile
export interface ProfileUpdateRequest {
  firstName?: string;
  lastName?: string;
  fullName?: string;
  gender?: Gender;
  phone?: string;
  dateOfBirth?: string;
  bloodType?: BloodType;
  allergies?: string;
  chronicConditions?: string;
  heightCm?: number;
  weightKg?: number;
  emergencyContactName?: string;
  emergencyContactPhone?: string;
  insuranceProvider?: string;
  insurancePolicyNumber?: string;
  medicalNotes?: string;
  avatarUrl?: string;
}

// Auth event types
export type AuthEventType =
  | 'SIGNED_IN'
  | 'SIGNED_OUT'
  | 'TOKEN_REFRESHED'
  | 'USER_UPDATED'
  | 'PASSWORD_RECOVERY';

// Auth change event
export interface AuthChangeEvent {
  event: AuthEventType;
  session: Session | null;
}

// Auth response
export interface AuthResponse<T = any> {
  data: T | null;
  error: AuthError | null;
}
