# [Mohmed Safwat (Bo3ly) - aifdrpp-v9 - @06/06/2026]

import json
import os
import sys
from pathlib import Path

try:
    from utils.environment import load_environment
except ModuleNotFoundError:
    p = Path(__file__).resolve()
    repo_root = None
    for _ in range(6):
        candidate = p
        if (candidate / "utils").exists():
            repo_root = str(candidate)
            break
        p = p.parent
    if repo_root is None:
        repo_root = str(Path(__file__).resolve().parents[2])
    if repo_root not in sys.path:
        sys.path.insert(0, repo_root)
    from utils.environment import load_environment


class Reporter:
    """
    Converts structured pipeline output into a medical-style report.

    If `GEMINI_API_KEY` is configured, the report is generated by Gemini.
    Otherwise the deterministic rule-based fallback is used.
    """

    def __init__(self, config=None):
        load_environment()
        self.config = config or {}
        report_cfg = self.config.get("report_generation", {}) or {}
        self.enabled = bool(report_cfg.get("enabled", True))
        self.provider = report_cfg.get("provider", "gemini")
        self.model_name = report_cfg.get("model", os.environ.get("GEMINI_MODEL", "gemini-2.5-flash"))

    def generate(self, structured_output):
        if self.enabled and self.provider == "gemini":
            llm_report = self._generate_with_gemini(structured_output)
            if llm_report:
                return llm_report

        return self._generate_fallback(structured_output)

    def translate_report(self, report_text: str, target_lang: str = "ar") -> str:
        """Translate an existing report paragraph into the target language using Gemini.

        Falls back to returning an empty string on any error.
        """
        api_key = os.environ.get("GEMINI_API_KEY")
        if not api_key or not report_text:
            return ""

        try:
            import google.generativeai as genai
        except Exception:
            return ""

        try:
            genai.configure(api_key=api_key)
            model = genai.GenerativeModel(self.model_name)
            prompt = (
                f"Translate the following radiology report paragraph from English to {target_lang}. "
                "Preserve clinical accuracy and do not add or remove findings. Reply with the translated text only.\n\n"
                f"{report_text}"
            )
            response = model.generate_content(prompt)
            text = getattr(response, "text", None)
            if text:
                return text.strip()
        except Exception:
            return ""

        return ""

    def _generate_with_gemini(self, structured_output):
        api_key = os.environ.get("GEMINI_API_KEY")
        if not api_key:
            return None

        try:
            import google.generativeai as genai

# [Mohmed Safwat (Bo3ly) - aifdrpp-v9 - @06/06/2026]

        except ImportError:
            return None

        try:
            genai.configure(api_key=api_key)
            model = genai.GenerativeModel(self.model_name)

            prompt = self._build_prompt(structured_output)
            response = model.generate_content(prompt)
            text = getattr(response, "text", None)
            if text:
                return text.strip()
        except Exception:
            return None

        return None

    def _build_prompt(self, structured_output):

        return (
            "You are an AI radiology reporting assistant. "

            "Generate a concise professional radiology-style "
            "clinical findings summary based ONLY on the provided "
            "structured fracture-analysis JSON. "

            "STRICT RULES: "

            "Use ONLY the information explicitly present in the JSON. "
            "Do NOT invent findings, diagnoses, anatomical locations, "
            "measurements, or recommendations. "

            "Use conservative medical wording. "

            "If confidence is moderate or low, use cautious phrasing such as "
            "'possible', 'suggestive of', 'may represent', or "
            "'cannot be excluded'. "

            "Do NOT state uncertain findings as definitive. "

            "Mention the detected body part. "
            "Mention the most likely fracture type if confidence is sufficient. "
            "Mention the number of detected fracture candidates. "
            "Mention low-confidence detections if present. "
            "Mention possible artifact or false-positive regions if appropriate. "

            "Keep the response concise and medically professional. "

            "Output ONLY one paragraph. "
            "No headings. "
            "No markdown. "
            "No bullet points. "
            "Minimum  70 words, and Maximum 120 words, Unless there are zero fractures, then clearly state that no fracture is identified without much words. "

            "If no fracture is detected, clearly state: "
            "'No radiographic evidence of fracture is identified "
            "based on the provided AI analysis.' "

            f"\n\nSTRUCTURED_JSON:\n"
            f"{json.dumps(structured_output, ensure_ascii=False, indent=2)}"
        )


    def _generate_fallback(self, structured_output):
        fracture_type = structured_output.get("fracture_type", {})
        fractures = structured_output.get("fractures", [])
        if not fractures:
            return (
                "No radiographic evidence of fracture is identified based on the provided AI analysis. "
                "The image does not show a confirmed fracture candidate."
            )

        type_label = fracture_type.get("label") or "fracture"
        type_confidence = fracture_type.get("confidence")
        candidate_count = len(fractures)

        summary = f"The provided AI analysis identifies {candidate_count} fracture candidate"
        summary += "s" if candidate_count != 1 else ""
        summary += f" with a {type_label} fracture pattern"
        if type_confidence is not None:
            summary += f" at {type_confidence:.2f} confidence"
        summary += "."

        return summary


# [Mohmed Safwat (Bo3ly) - aifdrpp-v9 - @06/06/2026]