/**
 * Authentication Types
 * TypeScript definitions for auth-related data
 */

import { User as SupabaseUser, Session } from '@supabase/supabase-js';

// Account type — matches the account_type enum in Supabase user_accounts table
export type AccountType = 'patient' | 'doctor' | 'pharmacist' | 'admin';

// Account status — matches the account_status enum in Supabase user_accounts table
export type AccountStatus = 'pending' | 'active' | 'suspended' | 'rejected';

// Database row type for profiles table
export interface ProfileRow {
  id: string;
  email: string;
  first_name: string | null;
  last_name: string | null;
  full_name: string | null;
  gender: string | null;
  phone: string | null;
  date_of_birth: string | null;
  avatar_url: string | null;
  created_at: string;
  updated_at: string;
}

// Database schema type (will be auto-generated by Supabase CLI)
export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: ProfileRow;
        Insert: Omit<ProfileRow, 'created_at' | 'updated_at'>;
        Update: Partial<Omit<ProfileRow, 'created_at'>>;
      };
    };
  };
};

// User profile from database
export interface UserProfile {
  id: string;
  email: string;
  firstName: string | null;
  lastName: string | null;
  fullName: string | null;
  gender: Gender | null;
  phone: string | null;
  dateOfBirth: string | null;
  avatarUrl: string | null;
  createdAt: string;
  updatedAt: string;
  // Authorization fields injected from JWT claims (custom_access_token_hook)
  accountType: AccountType | null;
  accountStatus: AccountStatus | null;
  mustChangePassword: boolean;
}

// Auth state (immutable — always replace via setState, never mutate)
export interface AuthState {
  readonly user: SupabaseUser | null;
  readonly session: Session | null;
  readonly profile: UserProfile | null;
  readonly loading: boolean;
  readonly error: AuthError | null;
}

// Auth error
export interface AuthError {
  readonly message: string;
  readonly code?: string;
  readonly status?: number;
}

// Gender options
export type Gender = 'male' | 'female';

export const GENDER_OPTIONS: { value: Gender; label: string }[] = [
  { value: 'male', label: 'Male' },
  { value: 'female', label: 'Female' },
];


// Sign up credentials
export interface SignUpCredentials {
  email: string;
  password: string;
  firstName: string;
  lastName: string;
  dateOfBirth: string;
  gender: Gender;
  countryCode: string;
  phone: string;
  captchaToken?: string;
}

// Sign in credentials
export interface SignInCredentials {
  email: string;
  password: string;
  captchaToken?: string;
  rememberMe?: boolean;
}

// Password reset
export interface PasswordResetRequest {
  email: string;
  captchaToken?: string;
}

// Update password
export interface PasswordUpdateRequest {
  newPassword: string;
}

// Update profile
export interface ProfileUpdateRequest {
  firstName?: string;
  lastName?: string;
  fullName?: string;
  gender?: Gender;
  phone?: string;
  dateOfBirth?: string;
  avatarUrl?: string;
}

// Auth event types
export type AuthEventType =
  | 'SIGNED_IN'
  | 'SIGNED_OUT'
  | 'TOKEN_REFRESHED'
  | 'USER_UPDATED'
  | 'PASSWORD_RECOVERY';

// Auth change event
export interface AuthChangeEvent {
  event: AuthEventType;
  session: Session | null;
}

// Auth response (generic result wrapper — similar to Rust's Result<T, E>)
export interface AuthResponse<T = unknown> {
  readonly data: T | null;
  readonly error: AuthError | null;
}
